# This is a basic workflow to help you get started with Actions
name: CI-CD

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains multiple jobs
  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      # FE BUILD
      - name: Install dependencies
        working-directory: ./fb-fe
        run: |
          npm install
          npm ci
      # build and test the apps
      - name: build
        working-directory: ./fb-fe
        run: |
          npm run build
#          npm run test
    push_to_Docker_Hub:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      # Build Docker image and push to Docker Hub only if the app build and test successfully
      needs: [build_test]
      
      steps:
        # Step 1: Checkout the repository
        - name: Checkout repository
          uses: actions/checkout@v3

        # Step 2: Set up QEMU for multi-platform builds
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2

        # Step 3: Set up Docker Buildx for building images
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        # Step 4: Log in to Docker Hub
        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        # Step 5: Build and push Docker image to Docker Hub
        - name: Build and push Docker image
          id: docker_build
          uses: docker/build-push-action@v6
          working-directory: ./fb-be
          with:
            context: ./  # Adjust context if needed to reduce build size
            file: ./Dockerfile
            push: true  # Push image to Docker Hub
            tags: ${{ secrets.DOCKERHUB_USERNAME }}/filebot-webui:latest

        # Step 6: Run the image in a container and test it
        - name: Run the Docker image and test endpoints
          uses: addnab/docker-run-action@v3
          working-directory: ./fb-be
          with:
            image: ${{ secrets.DOCKERHUB_USERNAME }}/filebot-webui:latest
            run: |
              echo "Running the Docker image"
              echo "Testing the Node.js app endpoints"
              echo "Image digest: ${{ steps.docker_build.outputs.digest }}" 
